### ISSUE TITLE
uncaught error

### ISSUE THREAD

**Issue by koloideal** [gXLg/jutsu-api#5]
my code:

```
from jutsu_api import API

api = API()
print(api.search(keyword='bleach'))

```

error:

```
Traceback (most recent call last):
  File "/home/kolo/Python_Projects/JutsuBot/main.py", line 5, in <module>
    print(api.search(keyword='bleach'))
  File "/home/kolo/.cache/pypoetry/virtualenvs/jutsubot-OONaC2W_-py3.12/lib/python3.12/site-packages/jutsu_api/__init__.py", line 289, in __repr__
    return f"{self.name.name} - {self.name.orig} {self.years}:\n{self.content}"
                                                                 ^^^^^^^^^^^^
  File "/home/kolo/.cache/pypoetry/virtualenvs/jutsubot-OONaC2W_-py3.12/lib/python3.12/site-packages/jutsu_api/__init__.py", line 359, in content
    self._fetch()
  File "/home/kolo/.cache/pypoetry/virtualenvs/jutsubot-OONaC2W_-py3.12/lib/python3.12/site-packages/jutsu_api/__init__.py", line 388, in _fetch
    a = Utils.parse_anime(t, self._cache_name.id, full = True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kolo/.cache/pypoetry/virtualenvs/jutsubot-OONaC2W_-py3.12/lib/python3.12/site-packages/jutsu_api/__init__.py", line 69, in parse_anime
    title = re.findall("\\<h2 class=\"b-b-title the-anime-season center\"( title=\".*?\")?\\>(.*?)( \\(.*?\\))?\\</h2\\>", ht)[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by gXLg** [comment]
Fixed in the new 2.4 version. Please update
